# Colorscheme
colorscheme one-dark
# save a bit of window space by removing clippy from popups
set-option global ui_options ncurses_assistant=none
# Default tab size
set-option global tabstop 4
# Indent is a tab character
set-option global indentwidth 0
# Enable auto-closing of matching chars (needs auto-pairs.kak installed)
enable-auto-pairs
# Matching chars that will be autoclosed
set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` ` “ ” ‘ ’ « » ‹ ›
# Hide the auto info box
set-option global autoinfo ""
# Auto reload buffers upon external modification
set-option global autoreload yes
# Always show autocomplete pop upn insert mode
set-option global autocomplete insert

add-highlighter global/ wrap -word -indent -width 80 -marker ' '
# Highlight matching chars 
add-highlighter global/ show-matching
# Color Combination for matching chars
set-face global MatchingChar rgb:0d316b,rgb:adb3ff+b

add-highlighter global/ number-lines -min-digits 1 -hlcursor -separator ' '

# Tab autocompletion
hook global InsertCompletionShow .* %{
    try %{
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
        hook -once -always window InsertCompletionHide .* %{
            unmap window insert <tab> <c-n>
            unmap window insert <s-tab> <c-p>
        }
    }
}
